#!/bin/bash

#Attempt Renewal
echo 'Attempting renewal'

RENEWAL=`docker run --rm --name certbot -v /opt/nextcloud-spreed-signaling/nginx/www:/var/www/certbot -v /opt/nextcloud-spreed-signaling/certbot/conf/:/etc/letsencrypt -v /opt/nextcloud-spreed-signaling/coturn:/coturn certbot/certbot:latest renew --webroot --webroot-path /var/www/certbot/`

if [[ $RENEWAL == *"Congratulations"* ]]; then

echo 'Certificate was renewed. Copying Certificates and Restarting Containers'

#Copy certificate and private key to coturn
cp /opt/nextcloud-spreed-signaling/certbot/conf/live/signal.deeztek.com/fullchain.pem /opt/nextcloud-spreed-signaling/coturn/fullchain.pem && \
cp /opt/nextcloud-spreed-signaling/certbot/conf/live/signal.deeztek.com/privkey.pem /opt/nextcloud-spreed-signaling/coturn/privkey.pem && \

#Set certificate and key permissions
chmod 0644 -R /opt/nextcloud-spreed-signaling/coturn/ && \

#Restart Containers
docker container restart nextcloud_spreed_nginx && \
docker container restart nextcloud_spreed_coturn

else

echo 'Certificate was not renewed'

fi
