version: '3.7'

networks:

  TRAEFIKNETWORK:
    external: true

services:

  zabbix-mariadb-server:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: zabbix-mariadb-server
    logging:
      options:
        max-size: 10m
        max-file: "5"
    environment:
      - PUID=$PUID
      - PGID=$GUID
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=$TZ
      - MYSQL_DATABASE=${MYSQL_DATABASE} #optional
      - MYSQL_USER=${MYSQL_USER} #optional
      - MYSQL_PASSWORD=${MYSQL_PASSWORD} #optional
      #- REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
    volumes:
      - db-data:/config
      - db-backups:/db_backups
    ports:
     - 3306:3306
    networks:
     TRAEFIKNETWORK:
      aliases:
       - zabbix-mariadb-server
    restart: unless-stopped

  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-${ZBXVER}-latest
      build:
    context: .
    dockerfile: Dockerfile
  build: .
    container_name: zabbix-server
    logging:
      options:
        max-size: 10m
        max-file: "5"
    restart: unless-stopped
    depends_on:
      - zabbix-mariadb-server
    environment:
      DB_SERVER_HOST: zabbix-mariadb-server
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ZBX_CACHESIZE: 256M
      ZBX_VALUECACHESIZE: 256M
    ports:
      - "10051:10051"
    volumes:
      - zabbix-data:/var/lib/zabbix
      - ./odbc-mssql/odbc.ini:/etc/odbc.ini:ro #MSSQL odbc.ini file
      - ./odbc-mssql/odbcinst.ini:/etc/odbcinst.ini
      #- snmptraps:/var/lib/zabbix/snmptraps
      #- export:/var/lib/zabbix/export
    networks:
     TRAEFIKNETWORK:
      aliases:
       - zabbix-server

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-${ZBXVER}-latest
    container_name: zabbix-web
    logging:
      options:
        max-size: 10m
        max-file: "5"
    restart: unless-stopped
    depends_on:
      - zabbix-mariadb-server
      - zabbix-server
    environment:
      PUID: ${PUID}
      PGID: ${GUID}
      DB_SERVER_HOST: zabbix-mariadb-server
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: ${PHP_TZ}
    ports:
      - "${ZABBIX_FRONTEND_PORT}:8080"
    volumes:
      - zabbix-web:/usr/share/zabbix
    networks:
     TRAEFIKNETWORK:
      aliases:
       - zabbix-web
    labels:
      - "com.zabbix.company=MSRA"
      - "com.zabbix.component=zabbix-server"

      - "traefik.enable=true"
      - "traefik.docker.network=TRAEFIKNETWORK"

      # Routers
      - "traefik.http.routers.zabbix.entrypoints=http"
      - "traefik.http.routers.zabbix.rule=Host(`${HOST}.${DOMAIN}`)"
      - "traefik.http.routers.zabbix.middlewares=zabbix-https-redirect"

      - "traefik.http.routers.zabbix-secure.entrypoints=https"
      - "traefik.http.routers.zabbix-secure.rule=Host(`${HOST}.${DOMAIN}`)"
      - "traefik.http.routers.zabbix-secure.tls=true"
      #- "traefik.http.routers.zabbix-secure.tls.certresolver=le"  #Uncomment to enable Lets Encrypt integration with Traefik
      - "traefik.http.routers.zabbix-secure.service=zabbix"
      #- "traefik.http.routers.zabbix-secure.middlewares=add-zabbix"

      # Service definition
            - "traefik.http.services.zabbix.loadbalancer.server.port=8080"

      # Middleware definitions
      - "traefik.http.middlewares.zabbix-https-redirect.redirectscheme.scheme=https"
      #- "traefik.http.middlewares.add-zabbix.addPrefix.prefix=/zabbix"

  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-${ZBXVER}-latest
    container_name: zabbix-agent
    logging:
      options:
        max-size: 10m
        max-file: "5"
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      ZBX_HOSTNAME: "Zabbix server"
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: '10051'
      ZBX_SERVER_ACTIVE: zabbix-server
    ports:
      - "10050:10050"
    networks:
     TRAEFIKNETWORK:
      aliases:
       - zabbix-agent
       - zabbix-agent-passive
       - zabbix-agent-ubuntu

  ofelia:
    image: 'mcuadros/ofelia:latest'
    container_name: zabbix_cron
    logging:
      options:
        max-size: 10m
        max-file: "5"
    environment:
      - "TZ=America/New_York"
    volumes:
      # the ofelia config file
      - ./ofelia_config/config.ini:/etc/ofelia/config.ini
      # your docker reg credentials
      #- /home/centos/.docker/config.json:/root/.docker/config.json
      # the docker socket so ofelia can docker run ...
      - /var/run/docker.sock:/var/run/docker.sock
      # if you want to write a log for eace execution and view logs on the log -> I recommend to set this value
      - ofelia-logs:/tmp/logs
    restart: unless-stopped

volumes:


  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/zabbix-docker/db_data

  db-backups:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/zabbix-docker/db_backups

  zabbix-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/zabbix-docker/zabbix_data


  zabbix-web:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/zabbix-docker/zabbix_web


  ofelia-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/zabbix-docker/ofelia_logs


