version: "2"

networks:
  proxy:
    external: true


services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=${DBUSER}
      - DB_PASS=${DBPASS}
      - DB_DATABASE=${DBDATABASE}
      - APP_URL=https://${HOST}.${DOMAIN}
    volumes:
      - ./config:/config
    networks:
      - proxy
    #ports:
      #- 6875:80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      # Routers
      - "traefik.http.routers.bookstack.entrypoints=http"
      - "traefik.http.routers.bookstack.rule=Host(`${HOST}.${DOMAIN}`)"
      - "traefik.http.routers.bookstack.middlewares=bookstack-https-redirect"
      - "traefik.http.routers.bookstack-secure.entrypoints=https"
      - "traefik.http.routers.bookstack-secure.rule=Host(`${HOST}.${DOMAIN}`)"
      - "traefik.http.routers.bookstack-secure.tls=true"
      #- "traefik.http.routers.bookstack-secure.tls.certresolver=le"
      - "traefik.http.routers.bookstack-secure.service=bookstack"

      # Service definition
      - "traefik.http.services.bookstack.loadbalancer.server.port=80"

      # Middleware definitions
      - "traefik.http.middlewares.bookstack-https-redirect.redirectscheme.scheme=https"

      - "traefik.passHostHeader=true"

      # Watchtower
      #- "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MYSQLROOTPASS}
      - TZ=Europe/London
      - MYSQL_DATABASE=${DBDATABASE}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
    volumes:
      - ./dbdata:/config
      - ./db_backups:/db_backups
    networks:
      - proxy
    restart: unless-stopped
  
  ofelia:
    image: 'mcuadros/ofelia:latest'
    container_name: bookstack_mariadb_cron
    environment:
      - "TZ=$TZ"
    volumes:
      # the ofelia config file
      - ./ofelia_config/config.ini:/etc/ofelia/config.ini
      # your docker reg credentials
      #- /home/centos/.docker/config.json:/root/.docker/config.json
      # the docker socket so ofelia can docker run ...
      - /var/run/docker.sock:/var/run/docker.sock
      # if you want to write a log for eace execution and view logs on the log -> I recommend to set this value
      - ./ofelia_logs:/tmp/logs
    restart: unless-stopped

#Do not enable below unless you are connecting to an existing NFS share
#volumes:
  #db_backups:
    #driver: local
    #driver_opts:
      #type: nfs
      #o: addr=192.168.xxx.xxx,nolock,soft,rw
      #device: :/mnt/pool1/docker/bookstack
