version: '2'

networks:
  proxy:
    external: true

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_OPENLDAP_UID: ${PUID}
      LDAP_OPENLDAP_GID: ${GUID}
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "${LDAPORGANIZATION}"
      LDAP_DOMAIN: "${LDAPDOMAIN}"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "${LDAPADMINPASSWORD}"
      LDAP_CONFIG_PASSWORD: "${LDAPCONFIGPASSWORD}"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: 'binddn="cn=admin,cn=config" bindmethod=simple credentials="$$LDAP_CONFIG_PASSWORD" searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical'
      #LDAP_REPLICATION_DB_SYNCPROV: 'binddn="cn=admin,$$LDAP_BASE_DN" bindmethod=simple credentials="$$LDAP_ADMIN_PASSWORD" searchbase="$$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical'
      #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - ldap_dbase:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ldap_certs:/container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    # For replication to work correctly, domainname and hostname must be
    # set correctly so that "hostname"."domainname" equates to the
    # fully-qualified domain name for the host.
    domainname: "${LDAPHOSTDOMAIN}"
    hostname: "${LDAPHOST}"

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    #ports:
      #- "8080:80"
    depends_on:
      - openldap
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
          
      # Routers
      - "traefik.http.routers.phpldapadmin.entrypoints=http"
      - "traefik.http.routers.phpldapadmin.rule=Host(`${LDAPADMINHOST}.${LDAPADMINDOMAIN}`)"
      - "traefik.http.routers.phpldapadmin.middlewares=phpldapadmin-https-redirect"
      - "traefik.http.routers.phpldapadmin-secure.entrypoints=https"
      - "traefik.http.routers.phpldapadmin-secure.rule=Host(`${LDAPADMINHOST}.${LDAPADMINDOMAIN}`)"
      - "traefik.http.routers.phpldapadmin-secure.tls=true"
      #- "traefik.http.routers.phpldapadmin-secure.tls.certresolver=le"
      - "traefik.http.routers.phpldapadmin-secure.service=phpldapadmin"
          
      # Service definition
      - "traefik.http.services.phpldapadmin.loadbalancer.server.port=8080"
          
      # Middleware definitions
      - "traefik.http.middlewares.phpldapadmin-https-redirect.redirectscheme.scheme=https"
          
      - "traefik.passHostHeader=true"
          
      # Watchtower
      #- "com.centurylinklabs.watchtower.enable=true"

volumes:
  ldap_dbase:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./ldap_base

  ldap_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./ldap_config

  ldap_certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./ldap_certs