version: "2"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK_SET=022 #optional
    #user: "999"
    volumes:
      - ./config:/config
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      #Routers
      - "traefik.http.routers.heimdall.entrypoints=http"
      - "traefik.http.routers.heimdall.rule=Host(`heimdall.$DOMAIN`)"
      - "traefik.http.routers.heimdall.middlewares=heimdall-https-redirect"
      - "traefik.http.routers.heimdall-secure.entrypoints=https"
      - "traefik.http.routers.heimdall-secure.rule=Host(`heimdall.$DOMAIN`)"
      - "traefik.http.routers.heimdall-secure.tls=true"
      #- "traefik.http.routers.heimdall-secure.tls.certresolver=le"
      - "traefik.http.routers.heimdall-secure.service=heimdall"

      #Service definition
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"

      #Middleware definitions
      - "traefik.http.middlewares.heimdall-https-redirect.redirectscheme.scheme=https"

      #Authelia authentication
      #- "traefik.http.routers.heimdall-secure.middlewares=authelia@docker"

      # Watchtower
      #- "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true
